IMAGE_PIXEL_WIDTH = 50

WINDOW_WIDTH = 900
WINDOW_HEIGHT = 1000

HEADER_HEIGHT = 100
BOARD_HEIGHT = WINDOW_HEIGHT-HEADER_HEIGHT

MAX_ROW_COUNT = BOARD_HEIGHT//IMAGE_PIXEL_WIDTH
MAX_COL_COUNT = WINDOW_WIDTH//IMAGE_PIXEL_WIDTH

NUM_OF_BOMBS = 70

WHITE = (255, 255, 255)